name: jangora
description: "Application Flutter pour la formation en ligne avec suivi de progression."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3  # Mise à jour pour compatibilité

dependencies:
  flutter:
    sdk: flutter

  # Firebase (versions stables)
  firebase_core: ^2.32.0  # Version compatible avec votre SDK
  firebase_auth: ^4.16.0   # Version compatible

  # UI et Utilitaires
  google_fonts: ^6.1.0
  provider: ^6.1.1
  flutter_svg: ^2.0.7
  iconsax: ^0.0.8

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Gardé en v4 pour compatibilité

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpg
    - assets/images/